spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/DB_mobile_office?serverTimezone=GMT%2B8&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: HTML5
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mobileoffice:
  file-path:
    employee: F:/mobileoffice/employee
  global-exception:
    assert-exception: true